# Generated by Django 5.0 on 2023-12-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[('like', 1), ('unlike', -1)]),
        ),
    ]
