# Generated by Django 5.0 on 2023-12-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(1, 1), (-1, -1)]),
        ),
    ]
